title: Vlad Feinberg
description: Vlad's Blog
author: Vlad Feinberg
about: dev | ml | math

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "LICENSE", "Gemfile", "Gemfile.lock"]

urls:
    - text: Home
      url: /
      icon: fa-home
      layout: post
    - text: About
      url: /about
      icon: fa-comments
    - text: Categories
      url: /categories
      icon: fa-folder
    - text: Featured
      url: /featured
      icon: fa-star
    - text: Search
      url: /search.html
      icon: fa-search
    # vyom: temporary disable xml feed from header site navigation
    # - text: XML Feed
    #   url: /feed.xml
    #   icon: fa-feed

github: https://github.com/vlad17

social:
    - icon: fa-linkedin
      link: 'https://www.linkedin.com/in/vladimir-feinberg-64b92895'
    - icon: fa-stack-exchange
      link: 'http://stackexchange.com/users/1611424/vf1'
    - icon: fa-github
      link: 'https://github.com/vlad17'

share:
  twitter_username: \#
  fb_appid: 000000000000

#url: "https://vlad17.github.io"
url: "https://amazing-hoover-335b7f.netlify.app"

enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap

permalink: /:year/:month/:day/:title.html
# update about page featured image content here
about_page_image_url: "/static/img/about-page.JPG"
about_page_image_caption: "My friends and I at Pinecrest Lake after a hike to Eagle Peak."
# vyom: 210623
# upwork project:
# featured image used on posts if no image is set for it in the post front matter
featured_image: "/static/img/logo.jpg"
# vyom: 210623
# upwork project:
# Set custom excerpts for posts
excerpt_separator: <!--more-->
# vyom: 210624 Add site level meta keywords if not set
global_meta_keywords: Vlad Feinberg, Princeton, Computer Science
# vyom: 210624 Add og:image
# site logo for og:image. site_url is added infront of this path. To enable external file links, {{ site_url }} needs to be removed from default.html file og:image meta tag
global_site_logo: "/static/img/logo.jpg"