title: Vlad Feinberg
description: Vlad's Blog
author: Vlad Feinberg
about: dev | ml | math

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "LICENSE", "Gemfile", "Gemfile.lock"]

urls:
    - text: Home
      url: /
      icon: fa-home
      layout: post
    - text: About
      url: /about
      icon: fa-comments
    - text: Categories
      url: /categories
      icon: fa-folder
    - text: Projects
      url: /projects
      icon: fa-desktop
    - text: Search
      url: /search.html
      icon: fa-search
    - text: XML Feed
      url: /feed.xml
      icon: fa-feed

github: https://github.com/vlad17

social:
    - icon: fa-linkedin
      link: 'https://www.linkedin.com/in/vladimir-feinberg-64b92895'
    - icon: fa-stack-exchange
      link: 'http://stackexchange.com/users/1611424/vf1'
    - icon: fa-github
      link: 'https://github.com/vlad17'

share:
  twitter_username: \#
  fb_appid: 000000000000

url: "https://vlad17.github.io"

enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap

permalink: /:year/:month/:day/:title.html
